  STId
     CreatedOn
      PatientId  
      History 
      GeneralHealth 
      OphthalmicHistory 
      Occupation 
      Driver 
      Sphere 
      Cylinder 
      Axis 
      Addition 
      DistanceVisionRE 
      DistanceVisionLE 
      DistanceVisionBinoc 
      DistanceVARE 
      DistanceVALE 
      DistanceVABinoc 
      NearVABinoc 
      NearVARE 
      NearVALE 
      NearVisionBinoc 
      NearVisionRE 
      NearVisionLE 
      OMBNearUnaided 
      OMBNearAided 
      OMBDistAided 
      OMBDistUnaided 
      OMBNotes 
      AdditionalTests 
      AutorefractSphereRE 
      AutorefractSphereLE 
      AutorefractCylRE 
      AutorefractCylLE 
      AutorefractAddRE 
      AutorefractAddLE 
      RetSphereRE 
      RetSphereLE 
      RetCylRE 
      RetCylLE 
      RetAxisRE 
      RetAxisLE 
      DropsUsed 
      SubjectSphereRE 
      SubjectSphereLE 
      SubjectCylRE 
      SubjectCylLE 
      SubjectAxisRE 
      SubjectAxisLE 
      SubjectAddRE 
      SubjectAddLE 
      RefractionNotes 
      FinalVARE 
      FinalVALE 
      FinalVABinoc  
      FinalOMBDist 
      FinalOMBNear 
      FinalOMBNotes 
      FinalSphereRE 
      FinalSphereLE 
      FinalCylRE 
      FinalCylLE 
      FinalAxisRE 
      FinalAxisLE 
      FinalAddRE 
      FinalAddLE 
      Dilated 
      DrugUsed 
      TimeDrugUsed 
      PupilExam 
      ACExam 
      IOPRE 
      IOPLE 
      IOPInstrument 
      IOPTime 
      Adnexa 
      LidsLashes 
      Conjunctiva 
      Cornea 
      Lens 
      Vitreous 
      OpticNerve 
      Macula 
      Vessels 
      Periphery 
      AdditionalTestsFinal 
      Advice 
      Recommendations 
      Referrals 
      Recall 